version: '3.7'
services:
    traefik:
        image: traefik:latest # Dernière version officielle de Traefik
        command: --api --docker --docker.swarmmode # On active l'interface web et on écoute Docker
        ports:
            - "80:80"       # HTTP port
            - "443:443"     # HTTPs port
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # Traefik peut écouter Docker
            - /etc/traefik/traefik.toml:/traefik.toml
            - /etc/traefik/acme.json:/acme.json
        deploy:
            placement:
                constraints: [node.role==manager]
            restart_policy:
                condition: any
            labels:
                - "traefik.enable=true"
                - "traefik.port=8080"
                - "traefik.entryPoint=http,https"
                - "traefik.docker.network=traefik_rp_network"
                - "traefik.backend=traefik"
                - "traefik.frontend.rule=Host:traefik.votre-domaine.fr"
                # http://www.htaccesstools.com/htpasswd-generator/
                - "traefik.frontend.auth.basic=compte:mot-de-passe"
        networks:
            - rp_network


networks:
    rp_network:
