version: '2'

services:
  wordpress:
    image: wordpress:latest
    networks:
      - private
    container_name: "${WORDPRESS_DB_HOST}_${APP_SERVICE}_wordpress"
    volumes:
      - "/var/www/${WORDPRESS_DB_HOST}/${APP_SERVICE}:/var/www/html"
    ports:
      - ${PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}_MariaDB"
      WORDPRESS_DB_NAME : "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"

networks:
  private:
    external:
      name: private
