version: "3.7"
services:
    portainer:
        image: portainer/portainer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "portainerdata:/data"
        networks:
            - traefik_network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: any
            labels:
                - "traefik.enable=true"
                - "traefik.port=9000"
                - "traefik.docker.network=traefik_rp_network"
                - "traefik.backend=portainer"
                - "traefik.frontend.rule=Host:portainer.votre-domaine.fr"

    agent:
        image: portainer/agent
        environment:
            AGENT_CLUSTER_ADDR: tasks.agent
        ports:
            - "9001:9001"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/lib/docker/volumes:/var/lib/docker/volumes"
        networks:
            - traefik_network
        deploy:
            mode: global
            placement:
                constraints: [node.platform.os == linux]

networks:
    traefik_network:
        external: true
        name: traefik_rp_network

volumes:
    portainerdata:
