version: '2.4'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/partage/:/data
  environment:
    - OPENVPN_PROVIDER=NORDVPN
    - OPENVPN_USERNAME=votre-mail
    - OPENVPN_PASSWORD=votre-mot-de-passe
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
    - TRANSMISSION_WEB_UI=transmission-web-control

 proxy:
  image: haugene/transmission-openvpn-proxy
  restart: always
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
