version: '3.7'
services:
    db-prod:
        image: mariadb:latest
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
        networks:
            - traefik_network
        volumes:
            - "${PATH_STOCKAGE}/db-prod:/var/lib/mysql"
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    db-qualif:
        image: mariadb:latest
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
        networks:
            - traefik_network
        volumes:
            - "${PATH_STOCKAGE}/db-qualif:/var/lib/mysql"
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    db-dev:
        image: mariadb:latest
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
        networks:
            - traefik_network
        volumes:
            - "${PATH_STOCKAGE}/db-dev:/var/lib/mysql"
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - traefik_network
        environment:
            MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
            PMA_HOSTS: "db-prod,db-qualif,db-dev"
        deploy:
            replicas: 1
            placement:
                constraints: [node.role==manager]
            restart_policy:
                condition: any
            labels:
                - "traefik.enable=true"
                - "traefik.port=80"
                - "traefik.entryPoint=http,https"
                - "traefik.docker.network=traefik_rp_network"
                - "traefik.backend=phpmyadmin"
                - "traefik.frontend.rule=Host:${URL_WEBSERVICE}"

networks:
    traefik_network:
        external: true
        name: traefik_rp_network
